version: "3.8"

services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ticket_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ticket_postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - ticket_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ticket_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ticket_pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - ticket_network
    
  backup:
    build: ./backup
    container_name: ticket_backup
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      BACKUP_RETENTION_DAYS: 7
      BACKUP_SCHEDULE: "0 0 * * *"
    volumes:
      - ./backups:/backups
    networks:
      - ticket_network
    depends_on:
      - db

volumes:
  ticket_postgres_data:
  ticket_pgadmin_data:

networks:
  ticket_network:
    driver: bridge
